/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/Client/GetState": {
    /** Get current client connection state */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tracker.Controllers.ClientController.IClientState"];
            "application/json": components["schemas"]["Tracker.Controllers.ClientController.IClientState"];
            "text/json": components["schemas"]["Tracker.Controllers.ClientController.IClientState"];
          };
        };
      };
    };
  };
  "/api/Client/WatchState": {
    /** Stream real-time client connection state changes */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/x-ndjson": components["schemas"]["Tracker.Controllers.ClientController.IClientState"];
          };
        };
      };
    };
  };
  "/api/Events/GetEventsList": {
    /** Get list of available tournaments/events */
    get: {
      parameters: {
        query?: {
          /** @description Whether to stream all results as NDJSON (ignores pagination) */
          stream?: boolean;
          /** @description Page number (1-based, default: 1) */
          page?: number;
          /** @description Number of items per page (default: 50, max: 200) */
          pageSize?: number;
          /** @description Whether to include total count in headers (requires enumeration, default: true) */
          includeCount?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tracker.Controllers.EventsController.ITournament"][];
            "application/json": components["schemas"]["Tracker.Controllers.EventsController.ITournament"][];
            "text/json": components["schemas"]["Tracker.Controllers.EventsController.ITournament"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
  [path: `/api/Events/GetEvent/${number}`]: {
    /** Get tournament by ID */
    get: {
      parameters: {
        path: {
          /** @description Tournament ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["MTGOSDK.API.Play.Event"];
            "application/json": components["schemas"]["MTGOSDK.API.Play.Event"];
            "text/json": components["schemas"]["MTGOSDK.API.Play.Event"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
          };
        };
      };
    };
  };
  [path: `/api/Events/GetTournamentState/${number}`]: {
    /** Get tournament state by ID */
    get: {
      parameters: {
        path: {
          /** @description Tournament ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tracker.Controllers.EventsController.ITournamentStateUpdate"];
            "application/json": components["schemas"]["Tracker.Controllers.EventsController.ITournamentStateUpdate"];
            "text/json": components["schemas"]["Tracker.Controllers.EventsController.ITournamentStateUpdate"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: never;
        };
      };
    };
  };
  [path: `/api/Events/GetEntryFee/${number}`]: {
    /** Get entry fee information for a tournament */
    get: {
      parameters: {
        path: {
          /** @description Tournament ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": string;
            "application/json": string;
            "text/json": string;
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
          };
        };
      };
    };
  };
  [path: `/api/Events/GetStandings/${number}`]: {
    /** Get tournament standings */
    get: {
      parameters: {
        query?: {
          /** @description Whether to stream results as NDJSON */
          stream?: boolean;
        };
        path: {
          /** @description Tournament ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["MTGOSDK.API.Play.Tournaments.StandingRecord"][];
            "application/json": components["schemas"]["MTGOSDK.API.Play.Tournaments.StandingRecord"][];
            "text/json": components["schemas"]["MTGOSDK.API.Play.Tournaments.StandingRecord"][];
          };
        };
      };
    };
  };
  "/api/Events/WatchTournamentUpdates": {
    /** Stream real-time tournament state updates */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/x-ndjson": components["schemas"]["Tracker.Controllers.EventsController.ITournamentStateUpdate"][];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: never;
        };
      };
    };
  };
  "/api/Events/WatchPlayerCount": {
    /** Stream real-time player count updates */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/x-ndjson": components["schemas"]["Tracker.Controllers.EventsController.ITournamentPlayerUpdate"][];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: never;
        };
      };
    };
  };
  [path: `/api/Events/OpenEvent/${number}`]: {
    /** Open a tournament in the MTGO client */
    post: {
      parameters: {
        path: {
          /** @description Tournament ID */
          id: number;
        };
      };
      responses: {
        /** @description No Content */
        204: {
          content: never;
        };
        /** @description Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
            "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "MTGOSDK.API.Collection.Card": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
      isOpenable?: boolean;
      isSealedProduct?: boolean;
      isDigitalObject?: boolean;
      isBooster?: boolean;
      isCard?: boolean;
      isTicket?: boolean;
      isTradeable?: boolean;
      hasPremiumOdds?: boolean;
      colors?: string | null;
      manaCost?: string | null;
      /** Format: int32 */
      convertedManaCost?: number;
      rulesText?: string | null;
      types?: (readonly string[]) | null;
      subtypes?: (readonly string[]) | null;
      artist?: string | null;
      /** Format: int32 */
      artId?: number;
      set?: components["schemas"]["MTGOSDK.API.Collection.Set"];
      collectorInfo?: string | null;
      /** Format: int32 */
      collectorNumber?: number;
      flavorText?: string | null;
      power?: string | null;
      toughness?: string | null;
      loyalty?: string | null;
      defense?: string | null;
      isToken?: boolean;
    };
    "MTGOSDK.API.Collection.CardQuantityPair": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      card?: components["schemas"]["MTGOSDK.API.Collection.Card"];
      /** Format: int32 */
      quantity?: number;
    };
    "MTGOSDK.API.Collection.Deck": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      format?: components["schemas"]["MTGOSDK.API.Play.PlayFormat"];
      /** Format: date-time */
      timestamp?: string;
      /** Format: int32 */
      itemCount?: number;
      /** Format: int32 */
      maxItems?: number;
      hash?: string | null;
      items?: (readonly components["schemas"]["MTGOSDK.API.Collection.CardQuantityPair"][]) | null;
      itemIds?: (readonly number[]) | null;
      getFrozenCollection?: (readonly components["schemas"]["MTGOSDK.API.Collection.CardQuantityPair"][]) | null;
      regions?: (readonly components["schemas"]["MTGOSDK.API.Collection.DeckRegion"][]) | null;
      /** Format: int32 */
      deckId?: number;
      isLegal?: boolean;
    };
    /** @enum {string} */
    "MTGOSDK.API.Collection.DeckRegion": "NotSet" | "MainDeck" | "Sideboard" | "CommandZone" | "Planechase" | "Vanguard" | "Hidden";
    "MTGOSDK.API.Collection.Set": {
      code?: string | null;
      name?: string | null;
      /** Format: date-time */
      releaseDate?: string;
      type?: components["schemas"]["MTGOSDK.API.Collection.SetType"];
      /** Format: int32 */
      age?: number;
      cards?: (readonly components["schemas"]["MTGOSDK.API.Collection.Card"][]) | null;
    };
    /** @enum {string} */
    "MTGOSDK.API.Collection.SetType": "NotSet" | "CoreSet" | "LargeExpansionSet" | "SmallExpansionSet" | "EventTicket" | "TestSet" | "Supplemental" | "PromotionalSet" | "Ancillary" | "FixedAncillary" | "Placeholder";
    "MTGOSDK.API.Play.Event": {
      /** Format: int32 */
      id?: number;
      /** Format: uuid */
      token?: string;
      format?: components["schemas"]["MTGOSDK.API.Play.PlayFormat"];
      description?: string | null;
      /** Format: int32 */
      totalPlayers?: number;
      players?: (readonly components["schemas"]["MTGOSDK.API.Users.User"][]) | null;
      registeredDeck?: components["schemas"]["MTGOSDK.API.Collection.Deck"];
      /** Format: int32 */
      minutesPerPlayer?: number;
      /** Format: int32 */
      minimumPlayers?: number;
      /** Format: int32 */
      maximumPlayers?: number;
      isCompleted?: boolean;
      isRemoved?: boolean;
      hasJoined?: boolean;
      isParticipant?: boolean;
      isEliminated?: boolean;
    };
    /** @enum {string} */
    "MTGOSDK.API.Play.Games.GameStatus": "Invalid" | "NotStarted" | "Started" | "Finished";
    /** @enum {string} */
    "MTGOSDK.API.Play.MatchState": "Invalid" | "JoinRequested" | "Joined" | "RemovalRequested" | "RecruitingFreezeRequested" | "WatchRequested" | "Watching" | "AwaitingMinimumPlayers" | "AwaitingMaximumPlayers" | "AwaitingTimer" | "AwaitingPlayerStart" | "AwaitingHostStart" | "HostStartSent" | "GameStarted" | "Resuming" | "Sideboarding" | "DeckBuilding" | "DeckSubmitted" | "DeckAccepted" | "GameReplayRequested" | "GameReplaying" | "MatchCompleted" | "ConcedeRequested" | "Queue" | "Tournament" | "PremierEvent" | "Drafting" | "ChallengeMade" | "ChallengeAcceptanceSent" | "ChallengeAccepted" | "ChallengeRejectionSent" | "ChallengeRetractionSent" | "ChallengeMadeByCurrentUser" | "ChallengeReceivedByCurrentUser" | "EventUnderway" | "CurrentUserEliminated" | "EventWaitingToStart" | "EventCompleted" | "Connecting" | "Connected" | "Terminal" | "GameCompleted" | "GameClosed";
    "MTGOSDK.API.Play.PlayFormat": {
      name?: string | null;
      code?: string | null;
      /** Format: int32 */
      minDeckSize?: number;
      /** Format: int32 */
      maxDeckSize?: number;
      /** Format: int32 */
      maxCopiesPerCard?: number;
      /** Format: int32 */
      maxSideboardSize?: number;
      type?: components["schemas"]["MTGOSDK.API.Play.PlayFormatType"];
      legalSets?: (readonly components["schemas"]["MTGOSDK.API.Collection.Set"][]) | null;
      basicLands?: (readonly components["schemas"]["MTGOSDK.API.Collection.Card"][]) | null;
    };
    /** @enum {string} */
    "MTGOSDK.API.Play.PlayFormatType": "Null" | "Constructed" | "Sealed" | "Draft";
    "MTGOSDK.API.Play.Tournaments.GameStandingRecord": {
      /** Format: int32 */
      id?: number;
      gameStatus?: components["schemas"]["MTGOSDK.API.Play.Games.GameStatus"];
      /** Format: date-span */
      completedDuration?: string | null;
      winnerIds?: (readonly number[]) | null;
    };
    "MTGOSDK.API.Play.Tournaments.MatchStandingRecord": {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      round?: number;
      state?: components["schemas"]["MTGOSDK.API.Play.MatchState"];
      hasBye?: boolean;
      players?: (readonly components["schemas"]["MTGOSDK.API.Users.User"][]) | null;
      winningPlayerIds?: (readonly number[]) | null;
      losingPlayerIds?: (readonly number[]) | null;
      gameStandingRecords?: (readonly components["schemas"]["MTGOSDK.API.Play.Tournaments.GameStandingRecord"][]) | null;
    };
    "MTGOSDK.API.Play.Tournaments.StandingRecord": {
      /** Format: int32 */
      rank?: number;
      player?: components["schemas"]["MTGOSDK.API.Users.User"];
      /** Format: int32 */
      points?: number;
      record?: string | null;
      opponentMatchWinPercentage?: string | null;
      gameWinPercentage?: string | null;
      opponentGameWinPercentage?: string | null;
      previousMatches?: (readonly components["schemas"]["MTGOSDK.API.Play.Tournaments.MatchStandingRecord"][]) | null;
    };
    "MTGOSDK.API.Users.Avatar": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      card?: components["schemas"]["MTGOSDK.API.Collection.Card"];
    };
    "MTGOSDK.API.Users.User": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      avatar?: components["schemas"]["MTGOSDK.API.Users.Avatar"];
      isGuest?: boolean;
      isBuddy?: boolean;
      isBlocked?: boolean;
      isLoggedIn?: boolean;
      lastLogin?: string | null;
    };
    "Microsoft.AspNetCore.Mvc.ProblemDetails": {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      [key: string]: unknown;
    };
    "Tracker.Controllers.ClientController.IClientState": {
      isConnected?: boolean;
      isInitialized?: boolean;
      /** Format: int32 */
      processId?: number | null;
      status?: string | null;
      /** Format: int64 */
      memoryUsage?: number | null;
      /** Format: int64 */
      workingSet?: number | null;
      /** Format: int64 */
      virtualMemory?: number | null;
    };
    "Tracker.Controllers.EventsController.IEventStructure": {
      name?: string | null;
      isConstructed?: boolean;
      isLimited?: boolean;
      isDraft?: boolean;
      isSealed?: boolean;
      isSingleElimination?: boolean;
      isSwiss?: boolean;
      hasPlayoffs?: boolean;
    };
    "Tracker.Controllers.EventsController.ITournament": {
      /** Format: int32 */
      id?: number;
      description?: string | null;
      format?: string | null;
      /** Format: int32 */
      minimumPlayers?: number;
      /** Format: int32 */
      totalPlayers?: number;
      /** Format: int32 */
      totalRounds?: number;
      eventStructure?: components["schemas"]["Tracker.Controllers.EventsController.IEventStructure"];
      /** Format: date-time */
      startTime?: string;
      /** Format: date-time */
      endTime?: string;
      state?: string | null;
      /** Format: int32 */
      currentRound?: number;
      /** Format: date-time */
      roundEndTime?: string;
      inPlayoffs?: boolean;
    };
    "Tracker.Controllers.EventsController.ITournamentPlayerUpdate": {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      totalPlayers?: number;
      /** Format: int32 */
      totalRounds?: number;
      /** Format: date-time */
      endTime?: string;
    };
    "Tracker.Controllers.EventsController.ITournamentStateUpdate": {
      /** Format: int32 */
      id?: number;
      state?: string | null;
      /** Format: int32 */
      currentRound?: number;
      /** Format: date-time */
      roundEndTime?: string;
      inPlayoffs?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
