/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Events/GetEventsList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of available tournaments/events */
        get: {
            parameters: {
                query?: {
                    /** @description Whether to stream results as NDJSON */
                    stream?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": ITournament[];
                        "application/json": ITournament[];
                        "text/json": ITournament[];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/Events/GetEvent/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tournament by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tournament ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Event;
                        "application/json": Event;
                        "text/json": Event;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": ProblemDetails;
                        "application/json": ProblemDetails;
                        "text/json": ProblemDetails;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/Events/GetEntryFee/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entry fee information for a tournament */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tournament ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": ProblemDetails;
                        "application/json": ProblemDetails;
                        "text/json": ProblemDetails;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/Events/GetStandings/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tournament standings */
        get: {
            parameters: {
                query?: {
                    /** @description Whether to stream results as NDJSON */
                    stream?: boolean;
                };
                header?: never;
                path: {
                    /** @description Tournament ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": StandingRecord[];
                        "application/json": StandingRecord[];
                        "text/json": StandingRecord[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Events/WatchTournamentUpdates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream real-time tournament state updates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ndjson": ITournamentStateUpdate[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Events/WatchPlayerCount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream real-time player count updates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ndjson": ITournamentPlayerUpdate[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/Events/OpenEvent/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a tournament in the MTGO client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tournament ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": ProblemDetails;
                        "application/json": ProblemDetails;
                        "text/json": ProblemDetails;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "MTGOSDK.API.Collection.Card": {
            /** Format: int32 */
            readonly id?: number;
            readonly name?: string | null;
            readonly description?: string | null;
            readonly isOpenable?: boolean;
            readonly isSealedProduct?: boolean;
            readonly isDigitalObject?: boolean;
            readonly isBooster?: boolean;
            readonly isCard?: boolean;
            readonly isTicket?: boolean;
            readonly isTradeable?: boolean;
            readonly hasPremiumOdds?: boolean;
            readonly colors?: string | null;
            readonly manaCost?: string | null;
            /** Format: int32 */
            readonly convertedManaCost?: number;
            readonly rulesText?: string | null;
            readonly types?: string[] | null;
            readonly subtypes?: string[] | null;
            readonly artist?: string | null;
            /** Format: int32 */
            readonly artId?: number;
            set?: Set;
            readonly collectorInfo?: string | null;
            /** Format: int32 */
            readonly collectorNumber?: number;
            readonly flavorText?: string | null;
            readonly power?: string | null;
            readonly toughness?: string | null;
            readonly loyalty?: string | null;
            readonly defense?: string | null;
            readonly isToken?: boolean;
        };
        "MTGOSDK.API.Collection.CardQuantityPair": {
            /** Format: int32 */
            readonly id?: number;
            readonly name?: string | null;
            card?: Card;
            /** Format: int32 */
            readonly quantity?: number;
        };
        "MTGOSDK.API.Collection.Deck": {
            /** Format: int32 */
            readonly id?: number;
            readonly name?: string | null;
            format?: PlayFormat;
            /** Format: date-time */
            readonly timestamp?: string;
            /** Format: int32 */
            readonly itemCount?: number;
            /** Format: int32 */
            readonly maxItems?: number;
            readonly hash?: string | null;
            readonly items?: CardQuantityPair[] | null;
            readonly itemIds?: number[] | null;
            readonly getFrozenCollection?: CardQuantityPair[] | null;
            readonly regions?: DeckRegion[] | null;
            /** Format: int32 */
            readonly deckId?: number;
            readonly isLegal?: boolean;
        };
        /** @enum {string} */
        "MTGOSDK.API.Collection.DeckRegion": "NotSet" | "MainDeck" | "Sideboard" | "CommandZone" | "Planechase" | "Vanguard" | "Hidden";
        "MTGOSDK.API.Collection.Set": {
            readonly code?: string | null;
            readonly name?: string | null;
            /** Format: date-time */
            readonly releaseDate?: string;
            type?: SetType;
            /** Format: int32 */
            readonly age?: number;
            readonly cards?: Card[] | null;
        };
        /** @enum {string} */
        "MTGOSDK.API.Collection.SetType": "NotSet" | "CoreSet" | "LargeExpansionSet" | "SmallExpansionSet" | "EventTicket" | "TestSet" | "Supplemental" | "PromotionalSet" | "Ancillary" | "FixedAncillary" | "Placeholder";
        "MTGOSDK.API.Play.Event": {
            /** Format: int32 */
            readonly id?: number;
            /** Format: uuid */
            readonly token?: string;
            format?: PlayFormat;
            readonly description?: string | null;
            /** Format: int32 */
            readonly totalPlayers?: number;
            readonly players?: User[] | null;
            registeredDeck?: Deck;
            /** Format: int32 */
            readonly minutesPerPlayer?: number;
            /** Format: int32 */
            readonly minimumPlayers?: number;
            /** Format: int32 */
            readonly maximumPlayers?: number;
            readonly isCompleted?: boolean;
            readonly isRemoved?: boolean;
            readonly hasJoined?: boolean;
            readonly isParticipant?: boolean;
            readonly isEliminated?: boolean;
        };
        /** @enum {string} */
        "MTGOSDK.API.Play.Games.GameStatus": "Invalid" | "NotStarted" | "Started" | "Finished";
        /** @enum {string} */
        "MTGOSDK.API.Play.MatchState": "Invalid" | "JoinRequested" | "Joined" | "RemovalRequested" | "RecruitingFreezeRequested" | "WatchRequested" | "Watching" | "AwaitingMinimumPlayers" | "AwaitingMaximumPlayers" | "AwaitingTimer" | "AwaitingPlayerStart" | "AwaitingHostStart" | "HostStartSent" | "GameStarted" | "Resuming" | "Sideboarding" | "DeckBuilding" | "DeckSubmitted" | "DeckAccepted" | "GameReplayRequested" | "GameReplaying" | "MatchCompleted" | "ConcedeRequested" | "Queue" | "Tournament" | "PremierEvent" | "Drafting" | "ChallengeMade" | "ChallengeAcceptanceSent" | "ChallengeAccepted" | "ChallengeRejectionSent" | "ChallengeRetractionSent" | "ChallengeMadeByCurrentUser" | "ChallengeReceivedByCurrentUser" | "EventUnderway" | "CurrentUserEliminated" | "EventWaitingToStart" | "EventCompleted" | "Connecting" | "Connected" | "Terminal" | "GameCompleted" | "GameClosed";
        "MTGOSDK.API.Play.PlayFormat": {
            readonly name?: string | null;
            readonly code?: string | null;
            /** Format: int32 */
            readonly minDeckSize?: number;
            /** Format: int32 */
            readonly maxDeckSize?: number;
            /** Format: int32 */
            readonly maxCopiesPerCard?: number;
            /** Format: int32 */
            readonly maxSideboardSize?: number;
            type?: PlayFormatType;
            readonly legalSets?: Set[] | null;
            readonly basicLands?: Card[] | null;
        };
        /** @enum {string} */
        "MTGOSDK.API.Play.PlayFormatType": "Null" | "Constructed" | "Sealed" | "Draft";
        "MTGOSDK.API.Play.Tournaments.GameStandingRecord": {
            /** Format: int32 */
            readonly id?: number;
            gameStatus?: GameStatus;
            /** Format: date-span */
            readonly completedDuration?: string | null;
            readonly winnerIds?: number[] | null;
        };
        "MTGOSDK.API.Play.Tournaments.MatchStandingRecord": {
            /** Format: int32 */
            readonly id?: number;
            /** Format: int32 */
            readonly round?: number;
            state?: MatchState;
            readonly hasBye?: boolean;
            readonly players?: User[] | null;
            readonly winningPlayerIds?: number[] | null;
            readonly losingPlayerIds?: number[] | null;
            readonly gameStandingRecords?: GameStandingRecord[] | null;
        };
        "MTGOSDK.API.Play.Tournaments.StandingRecord": {
            /** Format: int32 */
            readonly rank?: number;
            player?: User;
            /** Format: int32 */
            readonly points?: number;
            readonly record?: string | null;
            readonly opponentMatchWinPercentage?: string | null;
            readonly gameWinPercentage?: string | null;
            readonly opponentGameWinPercentage?: string | null;
            readonly previousMatches?: MatchStandingRecord[] | null;
        };
        /** @enum {string} */
        "MTGOSDK.API.Play.Tournaments.TournamentState": "NotSet" | "Fired" | "WaitingToStart" | "Drafting" | "Deckbuilding" | "DeckbuildingDeckSubmitted" | "WaitingForFirstRoundToStart" | "RoundInProgress" | "BetweenRounds" | "Finished";
        "MTGOSDK.API.Users.Avatar": {
            /** Format: int32 */
            readonly id?: number;
            readonly name?: string | null;
            card?: Card;
        };
        "MTGOSDK.API.Users.User": {
            /** Format: int32 */
            readonly id?: number;
            readonly name?: string | null;
            avatar?: Avatar;
            readonly isGuest?: boolean;
            readonly isBuddy?: boolean;
            readonly isBlocked?: boolean;
            readonly isLoggedIn?: boolean;
            readonly lastLogin?: string | null;
        };
        "Microsoft.AspNetCore.Mvc.ProblemDetails": {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        "Tracker.Controllers.EventsController.IEventStructure": {
            readonly name?: string | null;
            readonly isConstructed?: boolean;
            readonly isLimited?: boolean;
            readonly isDraft?: boolean;
            readonly isSealed?: boolean;
            readonly isSingleElimination?: boolean;
            readonly isSwiss?: boolean;
        };
        "Tracker.Controllers.EventsController.ITournament": {
            /** Format: int32 */
            readonly id?: number;
            readonly description?: string | null;
            readonly format?: string | null;
            /** Format: int32 */
            readonly minimumPlayers?: number;
            /** Format: int32 */
            readonly totalPlayers?: number;
            /** Format: int32 */
            readonly totalRounds?: number;
            eventStructure?: IEventStructure;
            /** Format: date-time */
            readonly startTime?: string;
            /** Format: date-time */
            readonly endTime?: string;
        };
        "Tracker.Controllers.EventsController.ITournamentPlayerUpdate": {
            /** Format: int32 */
            readonly id?: number;
            /** Format: int32 */
            readonly totalPlayers?: number;
            /** Format: int32 */
            readonly totalRounds?: number;
            /** Format: date-time */
            readonly endTime?: string;
        };
        "Tracker.Controllers.EventsController.ITournamentStateUpdate": {
            /** Format: int32 */
            readonly id?: number;
            state?: TournamentState;
            /** Format: int32 */
            readonly currentRound?: number;
            /** Format: date-time */
            readonly roundEndTime?: string;
            readonly inPlayoffs?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Card = components['schemas']['MTGOSDK.API.Collection.Card'];
export type CardQuantityPair = components['schemas']['MTGOSDK.API.Collection.CardQuantityPair'];
export type Deck = components['schemas']['MTGOSDK.API.Collection.Deck'];
export type DeckRegion = components['schemas']['MTGOSDK.API.Collection.DeckRegion'];
export type Set = components['schemas']['MTGOSDK.API.Collection.Set'];
export type SetType = components['schemas']['MTGOSDK.API.Collection.SetType'];
export type Event = components['schemas']['MTGOSDK.API.Play.Event'];
export type GameStatus = components['schemas']['MTGOSDK.API.Play.Games.GameStatus'];
export type MatchState = components['schemas']['MTGOSDK.API.Play.MatchState'];
export type PlayFormat = components['schemas']['MTGOSDK.API.Play.PlayFormat'];
export type PlayFormatType = components['schemas']['MTGOSDK.API.Play.PlayFormatType'];
export type GameStandingRecord = components['schemas']['MTGOSDK.API.Play.Tournaments.GameStandingRecord'];
export type MatchStandingRecord = components['schemas']['MTGOSDK.API.Play.Tournaments.MatchStandingRecord'];
export type StandingRecord = components['schemas']['MTGOSDK.API.Play.Tournaments.StandingRecord'];
export type TournamentState = components['schemas']['MTGOSDK.API.Play.Tournaments.TournamentState'];
export type Avatar = components['schemas']['MTGOSDK.API.Users.Avatar'];
export type User = components['schemas']['MTGOSDK.API.Users.User'];
export type ProblemDetails = components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails'];
export type IEventStructure = components['schemas']['Tracker.Controllers.EventsController.IEventStructure'];
export type ITournament = components['schemas']['Tracker.Controllers.EventsController.ITournament'];
export type ITournamentPlayerUpdate = components['schemas']['Tracker.Controllers.EventsController.ITournamentPlayerUpdate'];
export type ITournamentStateUpdate = components['schemas']['Tracker.Controllers.EventsController.ITournamentStateUpdate'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
