/** @file
  Copyright (c) 2025, Cory Bennett. All rights reserved.
  SPDX-License-Identifier: Apache-2.0
**/

export const MANA_SYMBOL_FILE_BY_TOKEN: Record<string, string> = {
  "0": "0.svg",
  "1": "1.svg",
  "10": "10.svg",
  "11": "11.svg",
  "12": "12.svg",
  "13": "13.svg",
  "14": "14.svg",
  "15": "15.svg",
  "16": "16.svg",
  "17": "17.svg",
  "18": "18.svg",
  "19": "19.svg",
  "2": "2.svg",
  "2/B": "2B.svg",
  "2/G": "2G.svg",
  "2/R": "2R.svg",
  "2/U": "2U.svg",
  "2/W": "2W.svg",
  "20": "20.svg",
  "3": "3.svg",
  "4": "4.svg",
  "5": "5.svg",
  "6": "6.svg",
  "7": "7.svg",
  "8": "8.svg",
  "9": "9.svg",
  "B": "B.svg",
  "B/G": "BG.svg",
  "B/G/P": "BGP.svg",
  "B/P": "BP.svg",
  "B/R": "BR.svg",
  "B/R/P": "BRP.svg",
  "C": "C.svg",
  "C/B": "CB.svg",
  "C/G": "CG.svg",
  "C/R": "CR.svg",
  "C/U": "CU.svg",
  "C/W": "CW.svg",
  "CHAOS": "CHAOS.svg",
  "E": "E.svg",
  "G": "G.svg",
  "G/P": "GP.svg",
  "G/U": "GU.svg",
  "G/U/P": "GUP.svg",
  "G/W": "GW.svg",
  "G/W/P": "GWP.svg",
  "H": "H.svg",
  "P": "P.svg",
  "PW": "PW.svg",
  "Q": "Q.svg",
  "R": "R.svg",
  "R/G": "RG.svg",
  "R/G/P": "RGP.svg",
  "R/P": "RP.svg",
  "R/W": "RW.svg",
  "R/W/P": "RWP.svg",
  "S": "S.svg",
  "T": "T.svg",
  "TK": "TK.svg",
  "U": "U.svg",
  "U/B": "UB.svg",
  "U/B/P": "UBP.svg",
  "U/P": "UP.svg",
  "U/R": "UR.svg",
  "U/R/P": "URP.svg",
  "W": "W.svg",
  "W/B": "WB.svg",
  "W/B/P": "WBP.svg",
  "W/P": "WP.svg",
  "W/U": "WU.svg",
  "W/U/P": "WUP.svg",
  "X": "X.svg"
}

export const MANA_SYMBOL_TOKENS = new Set([
  "0",
  "1",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "2",
  "2/B",
  "2/G",
  "2/R",
  "2/U",
  "2/W",
  "20",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "B",
  "B/G",
  "B/G/P",
  "B/P",
  "B/R",
  "B/R/P",
  "C",
  "C/B",
  "C/G",
  "C/R",
  "C/U",
  "C/W",
  "CHAOS",
  "E",
  "G",
  "G/P",
  "G/U",
  "G/U/P",
  "G/W",
  "G/W/P",
  "H",
  "P",
  "PW",
  "Q",
  "R",
  "R/G",
  "R/G/P",
  "R/P",
  "R/W",
  "R/W/P",
  "S",
  "T",
  "TK",
  "U",
  "U/B",
  "U/B/P",
  "U/P",
  "U/R",
  "U/R/P",
  "W",
  "W/B",
  "W/B/P",
  "W/P",
  "W/U",
  "W/U/P",
  "X"
])

export function getManaSymbolSvgPath(symbol: string): string | null {
  const fileName = MANA_SYMBOL_FILE_BY_TOKEN[symbol]
  return fileName ? `/mana-symbols/${fileName}` : null
}